POST http://localhost:4000/app/form
Content-Type:application/json

{
    "fullName":"Bob-Builder",
    "height":60,
    "age":30,
    "salary":30000,
    "penisLength":9,
    "gifts":true,
    "bodyFat":15
}